# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f02c9af68a93a073244af23185d42642245756c780f04430b56ec92761d2b0c14c3f617e7926482af760110ffe4bf6566bb395158b7f2a42ab6b48509f3a3ae9

test:
  secret_key_base: b6321cc0258b2dec3174d4d074ebad946b089f426201239b15f0c5dfc062bcd956b6a1ca03b2c19b087cfa1cb81dddf7cf324483a0400a8f4ef6e12cb5e75aea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
